name: medilink-health
services:
- name: backend
  source_dir: backend
  github:
    repo: NgangaKamau3/medilink-health
    branch: main
  run_command: uvicorn main:app --host 0.0.0.0 --port $PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: SECRET_KEY
    scope: RUN_TIME
    value: ${SECRET_KEY}
  - key: DB_HOST
    scope: RUN_TIME
    value: ${DB_HOST}
  - key: DB_USER
    scope: RUN_TIME
    value: ${DB_USER}
  - key: DB_PASSWORD
    scope: RUN_TIME
    value: ${DB_PASSWORD}
  - key: DB_NAME
    scope: RUN_TIME
    value: ${DB_NAME}
  - key: ALLOWED_ORIGINS
    scope: RUN_TIME
    value: ${ALLOWED_ORIGINS}

- name: frontend
  source_dir: frontend
  github:
    repo: NgangaKamau3/medilink-health
    branch: main
  build_command: npm install --legacy-peer-deps && npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs

databases:
- name: medilink-db
  engine: MYSQL
  version: "8"